<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-11T05:30:12Z" name="Default suite" finished-at="2021-03-11T05:30:30Z" duration-ms="17519">
    <groups>
    </groups>
    <test started-at="2021-03-11T05:30:12Z" name="Default test" finished-at="2021-03-11T05:30:30Z" duration-ms="17519">
      <class name="com.training.Demo_ExtentReports.SalesForceLogin">
        <test-method is-config="true" signature="initialize()[pri:0, instance:com.training.Demo_ExtentReports.SalesForceLogin@2d6c53fc]" started-at="2021-03-11T05:30:12Z" name="initialize" finished-at="2021-03-11T05:30:15Z" duration-ms="3186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="Login_01()[pri:0, instance:com.training.Demo_ExtentReports.SalesForceLogin@2d6c53fc]" started-at="2021-03-11T05:30:15Z" name="Login_01" finished-at="2021-03-11T05:30:23Z" duration-ms="7232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_01 -->
        <test-method signature="Login_02()[pri:0, instance:com.training.Demo_ExtentReports.SalesForceLogin@2d6c53fc]" started-at="2021-03-11T05:30:23Z" name="Login_02" finished-at="2021-03-11T05:30:29Z" duration-ms="6739" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login_TC02 FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login_TC02 FAILED
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at com.training.Demo_ExtentReports.SalesForceLogin.Login_02(SalesForceLogin.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_02 -->
        <test-method is-config="true" signature="closereport()[pri:0, instance:com.training.Demo_ExtentReports.SalesForceLogin@2d6c53fc]" started-at="2021-03-11T05:30:29Z" name="closereport" finished-at="2021-03-11T05:30:30Z" duration-ms="342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closereport -->
      </class> <!-- com.training.Demo_ExtentReports.SalesForceLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
